import Head from "next/head";
import Image from "next/image";
import Defaultbaner from "../components/defaultbaner";
import Footer from "../components/footer";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import $, { data } from "jquery";
import { findDOMNode } from "react-dom";
import Link from "next/link";
import Form from "react-bootstrap/Form";
import "bootstrap/dist/css/bootstrap.css";
import Button from "react-bootstrap/Button";
import Card from "react-bootstrap/Card";
import ListGroup from "react-bootstrap/ListGroup";
import Menu from "../components/menu";
import Axios from "axios";

export default function contact({ configurs }) {
  return (
    <>
      <Head>
        <title>cico </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_cico.png" />
        <meta charSet="utf-8" />
      </Head>
      <main className={styles.main}>
        <Defaultbaner
          title="Contacts"
          legende="Nous vous enttendons"
          facebook_link={configurs.facebook}
          twitter_link={configurs.twitter}
          linkedin_link={configurs.linkedin}
        />

        <div className="container_fluid" id="canvas_id">
          <div className="row">
            <div className="col-md-12">
              <div className="page-description_n">
                <div className="row">
                  <div className="col-md-6 col-sm-6">
                    <p className="p_titre">Contacter nos équipes</p>
                    <p>
                      Nous sommes une entreprise de génie civil, spécialisée
                      dans la construction, l’expertise immobilière, la
                      fabrication et la vente des matériaux de construction.
                      Créée en 2010, elle a son siège en Ville de Goma et des
                      antennes à Kinshasa, Bukavu et Kalemie. Nous avons une
                      couverture totale de toute la république Démocratique du
                      Congo à travers nos quatre bureaux.
                    </p>
                    <p>
                      Télephone :{" "}
                      <span className="bold">{configurs.telephone}</span> <br />
                      Email: <span className="bold">info@cicosarl.com</span>
                      <br />
                      <br />
                      Goma, RDC
                      <br />
                      {configurs.adress}
                    </p>
                  </div>
                  <div className="col-md-6 col-sm-">
                    <div className="mail_respons"></div>
                    <form
                      method="post"
                      action="http://localhost/fidbagraphics/2023/fevrier/cico/back-office/api-contact"
                    >
                      <div className="col-md-12">
                        <div className="form-group">
                          <label>
                            Nom & post-nom <span className="required"></span>
                          </label>
                          <input
                            type="text"
                            className="form-control contact_nom"
                            name="contact_nom"
                            placeholder="votre nom et post-nom "
                            required
                          />
                        </div>
                      </div>
                      <div className="col-md-12">
                        <div className="form-group">
                          <label>
                            Adresse mail <span className="required"></span>
                          </label>
                          <input
                            type="email"
                            className="form-control contact_email"
                            name="contact_email"
                            placeholder=" ex :  eliezerk58@gmail.com"
                            required
                          />
                        </div>
                      </div>
                      <div className="col-md-12">
                        <div className="form-group">
                          <label>Objet</label>
                          <input
                            type="text"
                            className="form-control contact_objet mt-3"
                            name="contact_objet"
                            focus=""
                            placeholder="Objet"
                            required
                          />
                        </div>
                      </div>
                      <div className="col-md-12">
                        <div className="form-group">
                          <label>
                            Votre message <span className="required"></span>
                          </label>
                          <textarea
                            className="form-control contact_message mt-3 mt-3 area"
                            name="contact_message"
                            required
                            placeholder="Veuillez placer ici votre message"
                          ></textarea>
                        </div>
                      </div>
                      <div className="col-md-12 mt-3">
                        <div className="form-group">
                          <input
                            type="hidden"
                            id="gg_recaptcha"
                            name="g_recaptcha"
                          />
                        </div>
                      </div>
                      <div className="col-md-12 mt-3">
                        <input
                          type="text"
                          value={configurs.email}
                          id=""
                          name="mail_to"
                          hidden
                        />
                      </div>

                      <div className="col-md-12">
                        <button
                          type="submit"
                          name="submitContact"
                          data-action="submit"
                          className="btn btn-warning submit_button"
                        >
                          Envoyer
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <Footer
          apropos={configurs.Apropos}
          facebook_link={configurs.facebook}
          twitter_link={configurs.twitter}
          linkedin_link={configurs.linkedin}
          adress={configurs.adress}
          phone_number={configurs.telephone}
          email={configurs.email}
        />
        <div className="container-fluid menu_footer">
          <Menu />
        </div>
      </main>
    </>
  );
}
export let getServerSideProps = async () => {
  const respons = await fetch(
    "https://cico-admin.ritach.net/api-v1?configs=cico"
  );
  // const contact_respons = await fetch(
  //   "http://localhost/fidbagraphics/2023/fevrier/cico/back-office/api-contact"
  // );
  const configurs = await respons.json();
  // const contact_response = await contact_respons.json();
  // console.log("message :", contact_response);
  return {
    props: {
      configurs,
      // contact_response,
    },
  };
};
