import Head from "next/head";
import Image from "next/image";
import Defaultbaner from "../components/defaultbaner";
import Footer from "../components/footer";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { post } from "jquery";
import Link from "next/link";
import Form from "react-bootstrap/Form";
import "bootstrap/dist/css/bootstrap.css";
import Button from "react-bootstrap/Button";
import Card from "react-bootstrap/Card";
import ListGroup from "react-bootstrap/ListGroup";
import Menu from "../components/menu";

export default function about({ configurs }) {
  return (
    <>
      <Head>
        <title>cico </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_cico.png" />
        <meta charSet="utf-8" />
      </Head>
      <main className={styles.main}>
        <Defaultbaner
          title="Qui sommes-nous ?"
          legende="Nous transformons les reves de nos clients en realité"
          facebook_link={configurs.facebook}
          twitter_link={configurs.twitter}
          linkedin_link={configurs.linkedin}
        />

        <div className="container_fluid">{configurs.Apropos}</div>
        <div class="question mb-5">
          Avez-vous une question ?{" "}
          <a href="contact" class="btn btn-warning">
            Nous contacter
          </a>
        </div>
        <Footer
          apropos={configurs.Apropos}
          facebook_link={configurs.facebook}
          twitter_link={configurs.twitter}
          linkedin_link={configurs.linkedin}
          adress={configurs.adress}
          phone_number={configurs.telephone}
          email={configurs.email}
        />
        <div className="container-fluid menu_footer">
          <Menu />
        </div>
      </main>
    </>
  );
}
export let getServerSideProps = async () => {
  const respons = await fetch(
    "https://cico-admin.ritach.net/api-v1?configs=cico"
  );
  const configurs = await respons.json();
  return {
    props: {
      configurs,
    },
  };
};
