import Head from "next/head";
import Image from "next/image";
import Defaultbaner from "../components/defaultbaner";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { post } from "jquery";
import Link from "next/link";
import Footer from "../components/footer";
import Menu from "../components/menu";

export default function Home({ configurs }) {
  return (
    <>
      <Head>
        <title>cico </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_cico.png" />
        <meta charSet="utf-8" />
      </Head>
      <main className={styles.main}>
        <Defaultbaner
          title="Nos services"
          legende="Nous prénons en compte les besoins des clients"
          facebook_link={configurs.facebook}
          twitter_link={configurs.twitter}
          linkedin_link={configurs.linkedin}
        />
        <div className="section_container avec_marg">
          <div className="section_img service_un"></div>
          <div className="section_text">
            <h6>télécommunication</h6>
            <h1>
              Vous êtes une entreprise œuvrant dans la télécommunication ou le
              transport d'énergie ?
            </h1>
            <p>
              CICO CONSTRUCTION regorge en <br />
              son sein des experts en montage des pylônes <br />
              selon le besoin de votre entreprise. <br />
              Faites-nous confiance <br />
              et bénéficiez de nos services .
            </p>
            <br />
            {/* <ul className="ul_list">
              <li>la conception des plans, les dessins </li>
              <li>l'elaboration des plans detaillés de construction </li>
              <li>les études geotechniques du sol en laboratoire </li>
              <li>
                le dimmensionnement de l'ouvrage pour sa solidité, stabilité et
                durabilité{" "}
              </li>
            </ul> */}
          </div>
        </div>

        <div className="section_container avec_marg">
          <div className="section_text">
            {" "}
            <h6>Conception architecturale</h6>
            <h1>GENIE CIVIL EN GENERAL</h1>
            <p>
              Conception architecturale des ouvrages (bâtiments pour bureaux,
              <br />
              écoles, hôpitaux, hôtels, villas, appartements, salles de fêtes…),
              allant de réalisation des dessins
              <br /> techniques de construction, le dimensionnement et calcul de{" "}
              <br />
              stabilité des ouvrages, l’expertise et la contre-expertise, <br />{" "}
              la mise en œuvre et le suivi des travaux de construction.
            </p>
            {/* <ul className="ul_list">
              <li>la conception des plans, les dessins </li>
              <li>l'elaboration des plans detaillés de construction </li>
              <li>les études geotechniques du sol en laboratoire </li>
              <li>
                le dimmensionnement de l'ouvrage pour sa solidité, stabilité et
                durabulité{" "}
              </li>
            </ul> */}
          </div>
          <div className="section_img architecture"></div>
        </div>
        <div className="section_container avec_marg">
          <div className="section_img analyse"></div>
          <div className="section_text">
            {" "}
            <h6>à propos</h6>
            <h1>ANALYSE DE LABORATOIRE INDUSTRIES</h1>
            <p>
              Analyse technique des différents sols (CBR, limites d’Atteberg,{" "}
              <br />
              contrainte admissible des sols, sondage des sols, analyse
              <br />
              granulométrique…), analyse chimiques des sols de culture, essais
              <br />
              de dureté des matériaux de construction, essais de traction des
              <br />
              armatures, essais d’écrasement des béton.
            </p>
          </div>
        </div>
        <div className="section_container avec_marg ">
          <div className="section_text">
            {" "}
            <h6>des plans détaillés </h6>
            <h1>CONCEPTION ET ÉTUDES DES PROJETS DE CONSTRUCTION</h1>
            <p>
              Il s’agit de prendre en compte les <br /> besoins des clients, ses
              rêves et les matérialiser sur un plan. <br /> En fonction du
              besoin de l’ouvrage, <br /> des dimensions du site nous faisons la
              conception des plans, <br /> les dessins ; L’élaboration des plans
              détaillés de construction ; <br /> Les études géotechniques du sol
              en laboratoire ;
            </p>
          </div>
          <div className="section_img etude"></div>
        </div>
        <div className="section_container avec_marg ">
          <div className="section_img surveillance"></div>
          <div className="section_text">
            {" "}
            <h6>à propos</h6>
            <h1>SURVEILLANCE ET CONTRÔLE DES TRAVAUX.</h1>
            <p>
              Il peut s’avérer qu’un <br />
              client a déjà une entreprise qui <br />
              va s’occuper de la mise en œuvre de ses travaux. <br />
              Mais pour des raisons de garantie sur la qualité ou
              <br /> que le maitre d’ouvrage ne soit pas dans la même ville où{" "}
              <br />
              se déroulent les travaux <br /> veuille se rassurer que ces
              derniers sont exécutés selon les règles de l’art
            </p>
          </div>
        </div>
        <div className="section_container avec_marg">
          <div className="section_text">
            {" "}
            <h6>à propos</h6>
            <h1>EXPERTISE IMMOBILIÈRE</h1>
            <p>
              Il s’agit d’un service mis à la disposition des clients qui
              souhaitent valoriser leurs biens immobiliers. Par biens
              immobiliers, on voit les villas, les immeublescommerciaux, les
              appartements, les fermes pastorales, les champs, les concessions
              couverts par des titres fonciers.Par valorisation en sous-entend
              la détermination de la valeur vénale du bien
            </p>
          </div>
          <div className="section_img expertise"></div>
        </div>

        <Footer
          apropos={configurs.Apropos}
          facebook_link={configurs.facebook}
          twitter_link={configurs.twitter}
          linkedin_link={configurs.linkedin}
          adress={configurs.adress}
          phone_number={configurs.telephone}
          email={configurs.email}
        />
        <div className="container-fluid menu_footer">
          <Menu />
        </div>
      </main>
    </>
  );
}
export let getServerSideProps = async () => {
  const respons = await fetch(
    "https://cico-admin.ritach.net/api-v1?configs=cico"
  );

  const posts_response = await fetch(
    "https://cico-admin.ritach.net/api-v1?datas=all"
  );
  const configurs = await respons.json();
  const services = await posts_response.json();

  return {
    props: {
      configurs,
      services,
    },
  };
};
